### ISSUE TITLE
GPS data empty

### ISSUE THREAD

**Issue by louis-wiesmann** [mcdviral/mcdviral.github.io#6]
Thank you very much for your work! 
In many sequences the gps data seems broken (e.g. ntu_day_01). I was wondering if this is really the data you got or if simply something went wrong when splitting the bags.

Best regards,
Louis

**Comment by snakehaihai** [comment]
Hi Louis. For GPS, there is no guarantee of availability. We tried to collect data, but most of the time, GPS suffers from multi-path issues or fails to lock. That's why we had to survey the large area and perform CEVA fitting of the trajectory for ground truth. If you take a look at the campus, you'll see that most places have tall structures. One suggestion is to fit the available GPS data with the LiDAR trajectory and then generate pseudo-GPS data. This approach should be more reliable.


![image](https://github.com/user-attachments/assets/9aec76d3-6f50-4cf0-a2a7-ace7c30c754a)
![image](https://github.com/user-attachments/assets/3a83e322-361c-4dbd-8b8f-be7e13a7d477)

**Comment by brytsknguyen** [comment]
Hi,

For the NTU and KTH sequences, the prior maps were aligned with GPS coordinates of the real locations.

The original prior maps have very large coordinates, presumably in some global position convention, which we have added some offsets to it to produce the ground truth

NTU:
geo_offset = [-10900.00, -36000.00, -20];

KTH:
geo_offset = [-154100.0, -6581400.0, 0.0];

I suppose you can add these to the ground truth coordinates and use some conversions to get back the lat-lon coordinates. But I am not sure what the formulas are.

**Comment by louis-wiesmann** [comment]
@snakehaihai okay, yes this makes a lot of sense. Looks hard for the GPS. 

@brytsknguyen Thank you very much for providing the offset. I will probably not use the GPS for now since of the low reception but it might be helpful in future.
